%Creates test configurations for PUSCH, Type A, 40 MHz channel bandwidth, 30 kHz SCS.
%   These test cases are specified in TS38.104 V15.19.0, Table 8.2.1.2-6.

% SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
% SPDX-License-Identifier: BSD-3-Clause-Open-MPI

function testConfig = createTestConfigTable8_2_1_2_6()
    testConfig = { ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-6 Row 1', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A3-13', ...
            'SNR',                 -2.5 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-6 Row 2', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A4-13', ...
            'SNR',                 10 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-6 Row 3', ...
            'DelayProfile',        'TDLA30', ...
            'MaximumDopplerShift', 10, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A5-13', ...
            'SNR',                 12.4 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-6 Row 4', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A3-13', ...
            'SNR',                 -5.8 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-6 Row 5', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A4-13', ...
            'SNR',                 6.3 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-6 Row 6', ...
            'DelayProfile',        'TDLA30', ...
            'MaximumDopplerShift', 10, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A5-13', ...
            'SNR',                 8.5 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-6 Row 10', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             2, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A3-27', ...
            'SNR',                 1.3 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-6 Row 11', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NTxAnts',             2, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A4-27', ...
            'SNR',                 19.5 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-6 Row 12', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             2, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A3-27', ...
            'SNR',                 -2.3 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-6 Row 13', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NTxAnts',             2, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A4-27', ...
            'SNR',                 11.3 ...
        ), ...
    };
end % of function TestConfig = createTestConfigTable8_2_1_2_6()
