# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

spec:
  inputs:
    ocudu_path:
      type: string
      default: ocudu/ocudu
      description: "OCUDU repository path."
    ocudu_ref:
      type: string
      default: dev
      description: "OCUDU reference branch or tag."
---
include:
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/workflow.yml
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/docker.yml
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/static.yml
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/build.yml
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/version_check.yml
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/gitlab_settings/.gitlab-ci.yml
    inputs:
      ocudu_path: $[[ inputs.ocudu_path ]]
      ocudu_ref: $[[ inputs.ocudu_ref ]]
  - local: .gitlab/ci/version.yml

stages:
  - ci
  - static
  - matlab unit tests
  - test vectors
  - mex
  - private
  - public

variables:
  OCUDU_DIR: &ocudu_dir ${CI_PROJECT_DIR}/ocudu

################################################################################
# CI
################################################################################
version check:
  stage: ci
  extends: .version increased
  rules:
    - if: $CI_MERGE_REQUEST_LABELS =~ /ci-no-container/
      when: never
    - if: $ON_MR
      changes:
        - Dockerfile
  variables:
    FILE_PATH: .gitlab/ci/version.yml
    VARIABLE_NAME: MATLAB_IMAGE_VERSION

publish container:
  stage: ci
  extends: .docker-builder
  rules:
    - if: $CI_MERGE_REQUEST_LABELS =~ /ci-no-container/
      when: never
    - if: $ON_MR
      changes:
        - Dockerfile
  variables:
    NAME: ${MATLAB_RELEASE}
    VERSION: ${MATLAB_IMAGE_VERSION}
    BUILD_ARGS: MATLAB_RELEASE=${MATLAB_RELEASE};MATLAB_USER=${MATLAB_USER}
    KUBERNETES_EPHEMERAL_STORAGE_REQUEST: "80Gi"
    KUBERNETES_EPHEMERAL_STORAGE_LIMIT: "80Gi"
    MODE: publish

################################################################################
# Static
################################################################################
headers:
  extends: .headers

mex code format:
  extends: .code-format
  variables:
    CPP_SRC_DIR: +ocuduMEX/source
  rules:
    - if: $ON_MR
      changes:
        - +ocuduMEX/source/.clang-format
      when: never
    - if: $ON_MR

mex full code format:
  extends: .full-code-format
  variables:
    CPP_SRC_DIR: +ocuduMEX/source
  rules:
    - if: $ON_MR
      changes:
        - +ocuduMEX/source/.clang-format

mex include guards:
  extends: .include-guards
  variables:
    CPP_SRC_DIR: +ocuduMEX/source
    INPUT_PATH: include/ocudu_matlab

vector code format:
  extends: .full-code-format
  rules:
    - if: $ON_MR
  variables:
    CPP_SRC_DIR: ${OCUDU_DIR}/plugins/${CI_PROJECT_NAME}
  before_script:
    - &download_ocudu |
      mkdir -p ${OCUDU_DIR}
      cd ${OCUDU_DIR}
      git init > /dev/null 2>&1
      git remote add origin https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_SHELL_SSH_HOST}/$[[ inputs.ocudu_path ]].git > /dev/null 2>&1 || git remote set-url origin https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_SHELL_SSH_HOST}/$[[ inputs.ocudu_path ]].git > /dev/null
      git fetch --depth=1 origin $[[ inputs.ocudu_ref ]] > /dev/null
      git reset --hard FETCH_HEAD
      git config --global --add safe.directory ${OCUDU_DIR}
      cd ${CI_PROJECT_DIR}
    - &setup_vector_tests_plugin |
      mkdir -p ${OCUDU_DIR}/plugins && ln -s ${CI_PROJECT_DIR}/ocuduVectorTests ${OCUDU_DIR}/plugins/${CI_PROJECT_NAME}

vector include guards:
  extends: .include-guards
  rules:
    - if: $ON_MR
  variables:
    CPP_SRC_DIR: ${OCUDU_DIR}/plugins/${CI_PROJECT_NAME}
  before_script:
    - *download_ocudu
    - *setup_vector_tests_plugin

################################################################################
# matlab unit tests
################################################################################
run matlab unit tests:
  stage: matlab unit tests
  image: ${CI_REGISTRY_IMAGE}/${MATLAB_RELEASE}:${MATLAB_IMAGE_VERSION}
  tags:
    - matlab
  rules:
    - if: $ON_MR
  needs:
    - job: publish container
      artifacts: false
      optional: true
  script:
    - &inject_matlab_file |
      cp ${HARQ_ENTITY_PATH} ${CI_PROJECT_DIR}/apps/simulators/PUSCHBLER/+matlablicense/HARQEntity.m
    - |
      matlab -sd "./" -batch "addpath('.', '.gitlab/matlab'); \
      runsmoketests('matlab code', 'run_matlab_unit_tests.xml');" \
      -logfile matlablog.log
  artifacts:
    when: always
    paths:
      - matlablog.log
      - run_matlab_unit_tests.xml
    reports:
      junit: run_matlab_unit_tests.xml
    expire_in: 1 day

################################################################################
# test vectors
################################################################################
build test vectors:
  stage: test vectors
  image: ${CI_REGISTRY_IMAGE}/${MATLAB_RELEASE}:${MATLAB_IMAGE_VERSION}
  tags:
    - matlab
  variables:
    RANDOM_TESTS: "false"
  rules:
    - if: $ON_MR
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Nightly/
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Weekly/
      variables:
        RANDOM_TESTS: "true"
  needs:
    - job: publish container
      artifacts: false
      optional: true
  script:
    - export ARTIFACTSDIR="${CI_PROJECT_DIR}/artifacts"
    - mkdir -p $ARTIFACTSDIR
    - |
      matlab -sd ./ -batch "addpath('.', '.gitlab/matlab'); \
      runvectortests('testvector', ${RANDOM_TESTS}, 'build_test_vectors.xml', '${ARTIFACTSDIR}');" \
      -logfile matlab.log
  artifacts:
    when: always
    paths:
      - artifacts/
      - build_test_vectors.xml
      - matlablog.log
    reports:
      junit: build_test_vectors.xml
    expire_in: 10 days

build and run vector unit tests:
  extends: .build_and_unit_template
  stage: test vectors
  variables:
    OCUDU_DIR: *ocudu_dir
    OS: ubuntu-24.04
    COMPILER: gcc
    OCUDU_TARGET: all_vector_tests
    MARCH: x86-64-v3
    TEST_MODE: vectortest
    COMPARE_HEADERS: "True"
  timeout: 2 hours
  rules:
    - if: $ON_MR
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Nightly/
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Weekly/
      when: always
      variables:
        COMPARE_HEADERS: "False"
  needs:
    - job: build test vectors
  script:
    - *download_ocudu
    - *setup_vector_tests_plugin
    - DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --no-install-recommends rsync
    - rsync -av ./artifacts/ ${CI_PROJECT_DIR}/ocuduVectorTests/
    - |
      if [[ $COMPARE_TEST_VECTORS == "True" ]]; then
        if [[ $(git diff -U0 | grep -v -e "^\(+++\|---\|@@\|diff\|index\)" -e "^\(+\|-\)\(// This\|oid\|size\)" | wc -l) -gt 0 ]]; then
          echo "The new set of test vectors is not the standard one."
          git diff
          exit 1
        fi
      fi
    - build_ocudu
    - launch_tests_ocudu

################################################################################
# mex files
################################################################################
build ocudu with export on:
  stage: mex
  extends: .build_and_unit_template
  variables:
    OCUDU_DIR: *ocudu_dir
    OS: ubuntu-22.04
    COMPILER: gcc
    OCUDU_TARGET: ocudu_exported_libs
    ENABLE_EXPORT: "True"
    ENABLE_BACKWARD: "False"
    MARCH: x86-64-v3
    INFRASTRUCTURE_TAG: amd64-avx2
  rules:
    - if: $ON_MR
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Nightly/
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Weekly/
  script:
    - *download_ocudu
    - build_ocudu
    - rm -Rf $OCUDU_DIR/.git
  after_script: []
  needs: []
  artifacts:
    paths:
      - ocudu
    expire_in: 1 day

.build mex:
  stage: mex
  image: ${CI_REGISTRY_IMAGE}/${MATLAB_RELEASE}:${MATLAB_IMAGE_VERSION}
  variables:
    INFLUX_VERSION: 2.7.5
  tags:
    - matlab
  before_script:
    - *inject_matlab_file
    - |
      cd /tmp
      mkdir influxdb2-client-${INFLUX_VERSION}-linux-amd64
      wget https://dl.influxdata.com/influxdb/releases/influxdb2-client-${INFLUX_VERSION}-linux-amd64.tar.gz
      tar xvzf influxdb2-client-${INFLUX_VERSION}-linux-amd64.tar.gz -C influxdb2-client-${INFLUX_VERSION}-linux-amd64
      sudo cp influxdb2-client-${INFLUX_VERSION}-linux-amd64/influx /usr/local/bin/
      rm -Rf influxdb2-client-${INFLUX_VERSION}-linux-amd64*
    - export OCUDU_DIR=${CI_PROJECT_DIR}/ocudu
    - |
      sudo touch ${OCUDU_DIR}/build/ocudu.cmake
      cd ${CI_PROJECT_DIR}/+ocuduMEX/source
      mkdir -p build
      cd build
      cmake -GNinja -DOCUDU_BINARY_DIR="$OCUDU_DIR/build" -DMatlab_ROOT_DIR="/opt/matlab/" ..
      ninja -j $(( $(nproc) - 2 )) install
    - cd ${CI_PROJECT_DIR}
  after_script:
    - |
      find . -iname "conformance*.csv" -exec \
        influx write --host $INFLUXDB_URL --token $INFLUXDB_TOKEN --org $INFLUXDB_ORG \
        --bucket ci --file {} \;
  needs:
    - job: build ocudu with export on
    - job: publish container
      artifacts: false
      optional: true
  artifacts: &mex_artifacts
    when: always
    paths:
      - matlablog.log
      - build_mex_*.xml
      - tests/conformance/conformanceResults/conformance*.csv
    expire_in: 1 day

build mex basic tests:
  extends: .build mex
  rules:
    - if: $ON_MR
  script:
    - |
      matlab -sd "./" -batch "addpath('.', '.gitlab/matlab'); \
      runsmoketests('mex code', 'build_mex_basic_tests.xml');" \
      -logfile matlablog.log
  artifacts:
    <<: *mex_artifacts
    reports:
      junit: build_mex_basic_tests.xml

build mex full tests:
  extends: .build mex
  variables:
    RANDOM_TESTS: "false"
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Nightly/
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Weekly/
      variables:
        RANDOM_TESTS: "true"
  script:
    - |
      matlab -sd ./ -batch "addpath('.', '.gitlab/matlab'); \
      runvectortests('testmex', ${RANDOM_TESTS}, 'build_mex_full_tests.xml');" \
      -logfile matlab.log
  artifacts:
    <<: *mex_artifacts
    reports:
      junit: build_mex_full_tests.xml
    expire_in: 10 days

################################################################################
# conformance tests
################################################################################

.build mex conformance:
  extends: .build mex
  rules:
    - allow_failure: true
  variables:
    TEST: ""
    TESTMARKER: ""
    SUBSET: ""
  script:
    - |
      matlab -sd ./ -batch "addpath('.', '.gitlab/matlab'); \
      res = launchconformance('tests/conformance/${TEST}', '${SUBSET}', 'build_mex_conformance_xunit.xml', '${TESTMARKER}'); \
      postprocessconformance(res);" \
      -logfile matlablog.log
  artifacts:
    <<: *mex_artifacts
    reports:
      junit: build_mex_conformance_xunit.xml
    expire_in: 10 days
  timeout: 24h

build mex conformance even:
  extends: .build mex conformance
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /WeeklyEven/
  parallel:
    matrix:
      - TEST: "@CheckPUSCHConformance/CheckPUSCHConformance.m"
        TESTMARKER: "PLACEHOLDEREXAMPLE"
        SUBSET:
          - ".+Table8_2_1_2_1.+"       # Table TS38.104 V15.19.0 Table 8.2.1.2-1 (Type A,   5 MHz, 15 kHz)
          - ".+Table8_2_1_2_2.+"       # Table TS38.104 V15.19.0 Table 8.2.1.2-2 (Type A,  10 MHz, 15 kHz)
          - ".+Table8_2_1_2_3.+"       # Table TS38.104 V15.19.0 Table 8.2.1.2-3 (Type A,  20 MHz, 15 kHz)
          - ".+Table8_2_1_2_4.+"       # Table TS38.104 V15.19.0 Table 8.2.1.2-4 (Type A,  10 MHz, 30 kHz)
          - ".+Table8_2_1_2_5.+"       # Table TS38.104 V15.19.0 Table 8.2.1.2-5 (Type A,  20 MHz, 30 kHz)
          - ".+Table8_2_1_2_6.+"       # Table TS38.104 V15.19.0 Table 8.2.1.2-6 (Type A,  40 MHz, 30 kHz)
          - ".+Table8_2_1_2_7.+"       # Table TS38.104 V15.19.0 Table 8.2.1.2-7 (Type A, 100 MHz, 30 kHz)
          - ".+Table8_2_2_2_x.+"       # Table TS38.104 V15.19.0 Table 8.2.2.2-X (Type A. transform precoding)
          - ".+Table11_2_2_1_2_3.+"    # Table TS38.104 V15.19.0 Table 11.2.2.1.2-3 (Type B,  50 MHz, 120 kHz)
          - ".+Custom.+NumLayers=1\\)" # Custom 1 layer
          - ".+Custom.+NumLayers=2\\)" # Custom 2 layers
          - ".+Custom.+NumLayers=3\\)" # Custom 3 layers
          - ".+Custom.+NumLayers=4\\)" # Custom 4 layers
      - TEST: "CheckPUCCHF0Conformance.m"
        SUBSET:
          - ".detection.+struct(|_[1-2])\\)"   # Table TS38.104 V15.19.0 Table 8.3.2.2-1 (2 antennas, 1 symbol)
          - ".detection.+struct_[3-5]\\)"      # Table TS38.104 V15.19.0 Table 8.3.2.2-1 (2 antennas, 2 symbols)
          - ".detection.+struct_[6-8]\\)"      # Table TS38.104 V15.19.0 Table 8.3.2.2-1 (4 antennas, 1 symbol)
          - ".detection.+struct_(9|1[0-1])\\)" # Table TS38.104 V15.19.0 Table 8.3.2.2-1 (4 antennas, 2 symbols)
          - ".detection.+struct_1[2-3]\\)"     # Table TS38.104 V15.19.0 Table 8.3.2.2-2 (2 antennas, 1 symbol)
          - ".detection.+struct_1[4-5]\\)"     # Table TS38.104 V15.19.0 Table 8.3.2.2-2 (2 antennas, 1 symbol)
          - ".detection.+struct_1[6-7]\\)"     # Table TS38.104 V15.19.0 Table 8.3.2.2-2 (2 antennas, 2 symbols)
          - ".detection.+struct_1[8-9]\\)"     # Table TS38.104 V15.19.0 Table 8.3.2.2-2 (2 antennas, 2 symbols)
          - ".detection.+struct_2[0-1]\\)"     # Table TS38.104 V15.19.0 Table 8.3.2.2-2 (4 antennas, 1 symbol)
          - ".detection.+struct_22\\)"         # Table TS38.104 V15.19.0 Table 8.3.2.2-2 (4 antennas, 1 symbol)
          - ".detection.+struct_23\\)"         # Table TS38.104 V15.19.0 Table 8.3.2.2-2 (4 antennas, 1 symbol)
          - ".detection.+struct_2[4-5]\\)"     # Table TS38.104 V15.19.0 Table 8.3.2.2-2 (4 antennas, 2 symbols)
          - ".detection.+struct_26\\)"         # Table TS38.104 V15.19.0 Table 8.3.2.2-2 (4 antennas, 2 symbols)
          - ".detection.+struct_27\\)"         # Table TS38.104 V15.19.0 Table 8.3.2.2-2 (4 antennas, 2 symbols)
          - ".falseack.+struct(|_[1-2])\\)"    # Table TS38.104 V15.19.0 Table 8.3.2.2-1 (2 antennas, 1 symbol)
          - ".falseack.+struct_[3-5]\\)"       # Table TS38.104 V15.19.0 Table 8.3.2.2-1 (2 antennas, 2 symbols)
          - ".falseack.+struct_[6-8]\\)"       # Table TS38.104 V15.19.0 Table 8.3.2.2-1 (4 antennas, 1 symbol)
          - ".falseack.+struct_(9|1[0-1])\\)"  # Table TS38.104 V15.19.0 Table 8.3.2.2-1 (4 antennas, 2 symbols)
          - ".falseack.+struct_1[2-3]\\)"      # Table TS38.104 V15.19.0 Table 8.3.2.2-2 (2 antennas, 1 symbol)
          - ".falseack.+struct_1[4-5]\\)"      # Table TS38.104 V15.19.0 Table 8.3.2.2-2 (2 antennas, 1 symbol)
          - ".falseack.+struct_1[6-7]\\)"      # Table TS38.104 V15.19.0 Table 8.3.2.2-2 (2 antennas, 2 symbols)
          - ".falseack.+struct_1[8-9]\\)"      # Table TS38.104 V15.19.0 Table 8.3.2.2-2 (2 antennas, 2 symbols)
          - ".falseack.+struct_2[0-1]\\)"      # Table TS38.104 V15.19.0 Table 8.3.2.2-2 (4 antennas, 1 symbol)
          - ".falseack.+struct_22\\)"          # Table TS38.104 V15.19.0 Table 8.3.2.2-2 (4 antennas, 1 symbol)
          - ".falseack.+struct_23\\)"          # Table TS38.104 V15.19.0 Table 8.3.2.2-2 (4 antennas, 1 symbol)
          - ".falseack.+struct_2[4-5]\\)"      # Table TS38.104 V15.19.0 Table 8.3.2.2-2 (4 antennas, 2 symbols)
          - ".falseack.+struct_26\\)"          # Table TS38.104 V15.19.0 Table 8.3.2.2-2 (4 antennas, 2 symbols)
          - ".falseack.+struct_27\\)"          # Table TS38.104 V15.19.0 Table 8.3.2.2-2 (4 antennas, 2 symbols)
      - TEST: "CheckPUCCHF1Conformance.m"
        SUBSET:
          - ".+nack2ack.+struct(|_[1-2])\\)"  # TS38.104 V15.19.0 Tables 8.3.3.x.2-1 (15 kHz, 2 antennas)
          - ".+nack2ack.+struct_[3-5]\\)"     # TS38.104 V15.19.0 Tables 8.3.3.x.2-1 (15 kHz, 4 antennas)
          - ".+nack2ack.+struct_[6-7]\\)"     # TS38.104 V15.19.0 Tables 8.3.3.x.2-2 (30 kHz, 2 antennas)
          - ".+nack2ack.+struct_[8-9]\\)"     # TS38.104 V15.19.0 Tables 8.3.3.x.2-2 (30 kHz, 2 antennas)
          - ".+nack2ack.+struct_1[0-1]\\)"    # TS38.104 V15.19.0 Tables 8.3.3.x.2-2 (30 kHz, 4 antennas)
          - ".+nack2ack.+struct_12\\)"        # TS38.104 V15.19.0 Tables 8.3.3.x.2-2 (30 kHz, 4 antennas)
          - ".+nack2ack.+struct_13\\)"        # TS38.104 V15.19.0 Tables 8.3.3.x.2-2 (30 kHz, 4 antennas)
          - ".+detection.+struct(|_[1-2])\\)" # TS38.104 V15.19.0 Tables 8.3.3.x.2-1 (15 kHz, 2 antennas)
          - ".+detection.+struct_[3-5]\\)"    # TS38.104 V15.19.0 Tables 8.3.3.x.2-1 (15 kHz, 4 antennas)
          - ".+detection.+struct_[6-7]\\)"    # TS38.104 V15.19.0 Tables 8.3.3.x.2-2 (30 kHz, 2 antennas)
          - ".+detection.+struct_[8-9]\\)"    # TS38.104 V15.19.0 Tables 8.3.3.x.2-2 (30 kHz, 2 antennas)
          - ".+detection.+struct_1[0-1]\\)"   # TS38.104 V15.19.0 Tables 8.3.3.x.2-2 (30 kHz, 4 antennas)
          - ".+detection.+struct_1[2-3]\\)"   # TS38.104 V15.19.0 Tables 8.3.3.x.2-2 (30 kHz, 4 antennas)
          - ".+falseack.+struct(|_[1-2])\\)"  # TS38.104 V15.19.0 Tables 8.3.3.x.2-1 (15 kHz, 2 antennas)
          - ".+falseack.+struct_[3-5]\\)"     # TS38.104 V15.19.0 Tables 8.3.3.x.2-1 (15 kHz, 4 antennas)
          - ".+falseack.+struct_[6-9]\\)"     # TS38.104 V15.19.0 Tables 8.3.3.x.2-2 (30 kHz, 2 antennas)
          - ".+falseack.+struct_1[0-3]\\)"    # TS38.104 V15.19.0 Tables 8.3.3.x.2-2 (30 kHz, 4 antennas)

build mex conformance odd:
  extends: .build mex conformance
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /WeeklyOdd/
  parallel:
    matrix:
      - TEST: "CheckPUCCHF2Conformance.m"
        SUBSET:
          - ".+shortDetect.+struct(|_[1-5])\\)"           # TS38.104 V15.19.0 Tables 8.3.4.x.2-1 (15 kHz)
          - ".+shortDetect.+struct_([6-9]|1[0-3])\\)"     # TS38.104 V15.19.0 Tables 8.3.4.x.2-2 (30 kHz)
          - ".+shortFalseAlarm.+struct(|_[1-5])\\)"       # TS38.104 V15.19.0 Tables 8.3.4.x.2-1 (15 kHz)
          - ".+shortFalseAlarm.+struct_([6-9]|1[0-3])\\)" # TS38.104 V15.19.0 Tables 8.3.4.x.2-2 (30 kHz)
          - ".+long.+struct(|_[1-5])\\)"                  # TS38.104 V15.19.0 Tables 8.3.4.x.2-1 (15 kHz)
          - ".+long.+struct_([6-9]|1[0-3])\\)"            # TS38.104 V15.19.0 Tables 8.3.4.x.2-2 (30 kHz)
      - TEST: "CheckPUCCHF3Conformance.m"
        SUBSET:
          - ".+struct(|_[1-5])\\)"        # TS38.104 V15.19.0 Tables 8.3.5.2-1 (15 kHz, test 1, 2 antennas)
          - ".+struct_([6-9]|1[0-1])\\)"  # TS38.104 V15.19.0 Tables 8.3.5.2-1 (15 kHz, test 1, 4 antennas)
          - ".+struct_(1[8-9]|20)\\)"     # TS38.104 V15.19.0 Tables 8.3.5.2-1 (15 kHz, test 2, 2 antennas)
          - ".+struct_2[1-3]\\)"          # TS38.104 V15.19.0 Tables 8.3.5.2-1 (15 kHz, test 2, 4 antennas)
          - ".+struct_(2[7-9]|3[0-4])\\)" # TS38.104 V15.19.0 Tables 8.3.5.2-2 (30 kHz, test 1, 2 antennas)
          - ".+struct_(3[5-9]|4[0-2])\\)" # TS38.104 V15.19.0 Tables 8.3.5.2-2 (30 kHz, test 1, 4 antennas)
          - ".+struct_5[1-4]\\)"          # TS38.104 V15.19.0 Tables 8.3.5.2-2 (30 kHz, test 2, 2 antennas)
          - ".+struct_5[5-8]\\)"          # TS38.104 V15.19.0 Tables 8.3.5.2-2 (30 kHz, test 2, 4 antennas)
      - TEST: "CheckPUCCHF4Conformance.m"
        SUBSET:
          - ".+struct(|_[1-5])\\)"        # TS38.104 V15.19.0 Tables 8.3.6.2-1 (15 kHz, 2 antennas)
          - ".+struct_([6-9]|1[0-1])\\)"  # TS38.104 V15.19.0 Tables 8.3.6.2-1 (15 kHz, 4 antennas)
          - ".+struct_(1[8-9]|2[0-5])\\)" # TS38.104 V15.19.0 Tables 8.3.6.2-2 (30 kHz, 2 antennas)
          - ".+struct_(2[6-9]|3[0-3])\\)" # TS38.104 V15.19.0 Tables 8.3.6.2-2 (30 kHz, 4 antennas)
      - TEST: "CheckPRACHConformance.m"
        SUBSET:
          - ".detection.+struct(|_[1-3])\\)"         # TS38.104 V15.19.0 Table 8.4.2.2-1 (long)
          - ".detection.+struct_([4-9]|1[0-5])\\)"   # TS38.104 V15.19.0 Table 8.4.2.2-2 (short 15 kHz)
          - ".detection.+struct_(1[6-9]|2[0-7])\\)"  # TS38.104 V15.19.0 Table 8.4.2.2-2 (short 15 kHz)
          - ".detection.+struct_(2[8-9]|3[0-9])\\)"  # TS38.104 V15.19.0 Table 8.4.2.2-3 (short 30 kHz)
          - ".detection.+struct_(4[0-9]|5[0-1])\\)"  # TS38.104 V15.19.0 Table 8.4.2.2-3 (short 30 kHz)
          - ".detection.+struct_5[2-3]\\)"           # TS38.104 V15.19.0 Table 11.4.2.2-2 (short 120 kHz)
          - ".falsealarm.+struct(|_[1-3])\\)"        # TS38.104 V15.19.0 Table 8.4.2.2-1 (long)
          - ".falsealarm.+struct_[4-7]\\)"           # TS38.104 V15.19.0 Table 8.4.2.2-2 (short 15 kHz)
          - ".falsealarm.+struct_([8-9]|1[0-1])\\)"  # TS38.104 V15.19.0 Table 8.4.2.2-2 (short 15 kHz)
          - ".falsealarm.+struct_1[2-5]\\)"          # TS38.104 V15.19.0 Table 8.4.2.2-2 (short 15 kHz)
          - ".falsealarm.+struct_1[6-9]\\)"          # TS38.104 V15.19.0 Table 8.4.2.2-2 (short 15 kHz)
          - ".falsealarm.+struct_2[0-3]\\)"          # TS38.104 V15.19.0 Table 8.4.2.2-2 (short 15 kHz)
          - ".falsealarm.+struct_2[4-7]\\)"          # TS38.104 V15.19.0 Table 8.4.2.2-3 (short 15 kHz)
          - ".falsealarm.+struct_(2[8-9]|3[0-1])\\)" # TS38.104 V15.19.0 Table 8.4.2.2-3 (short 30 kHz)
          - ".falsealarm.+struct_3[2-5]\\)"          # TS38.104 V15.19.0 Table 8.4.2.2-3 (short 30 kHz)
          - ".falsealarm.+struct_3[6-9]\\)"          # TS38.104 V15.19.0 Table 8.4.2.2-3 (short 30 kHz)
          - ".falsealarm.+struct_4[0-3]\\)"          # TS38.104 V15.19.0 Table 8.4.2.2-3 (short 30 kHz)
          - ".falsealarm.+struct_4[4-7]\\)"          # TS38.104 V15.19.0 Table 8.4.2.2-3 (short 30 kHz)
          - ".falsealarm.+struct_(4[8-9]|5[0-1])\\)" # TS38.104 V15.19.0 Table 8.4.2.2-3 (short 30 kHz)
          - ".falsealarm.+struct_5[2-3]\\)"          # TS38.104 V15.19.0 Table 11.4.2.2-2 (short 120 kHz)
