%Creates test configurations for PUSCH, Type A, transform precoding enabled.
%   These test cases are specified in TS38.104 V15.19.0, Table 8.2.2.2-x.

%
%   Copyright 2021-2026 Software Radio Systems Limited
%
%   By using this file, you agree to the terms and conditions set
%   forth in the LICENSE file which can be found at the top level of
%   the distribution.
%

function testConfig = createTestConfigTable8_2_2_2_x()
    testConfig = {
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.2.2-1 Row 1', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A3-31', ...
            'SNR',                 -2.4 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.2.2-1 Row 2', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A3-31', ...
            'SNR',                 -5.7 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.2.2-2 Row 1', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A3-32', ...
            'SNR',                 -2.5 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.2.2-2 Row 2', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A3-32', ...
            'SNR',                 -5.7 ...
        ), ...
    };
end % of function TestConfig = createTestConfigTable8_2_2_2_x()
