%Creates test configurations for PUSCH, Type B, 50 MHz channel bandwidth, 120 kHz SCS.
%   These test cases are specified in TS38.104 V15.19.0 and V19.0.0, Table 11.2.2.1.2-3.
%
%   Commented configurations require PT-RS, which is currently not implemented.

% SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
% SPDX-License-Identifier: BSD-3-Clause-Open-MPI

function testConfig = createTestConfigTable11_2_2_1_2_3()
    testConfig = { ...
        struct( ...
            'Name',                    'TS38.104 V15.19.0 Table 11.2.2.1.2-3 Row 1', ...
            'DelayProfile',            'TDLA30', ...
            'MaximumDopplerShift',     300, ...
            'NTxAnts',                 1, ...
            'NRxAnts',                 2, ...
            'DMRSAdditionalPosition',  0, ...
            'EnablePTRS',              false, ...
            'FRC',                     'G-FR2-A3-3', ...
            'SNR',                     -1.8 ...
        ), ...
        struct( ...
            'Name',                    'TS38.104 V15.19.0 Table 11.2.2.1.2-3 Row 2', ...
            'DelayProfile',            'TDLA30', ...
            'MaximumDopplerShift',     300, ...
            'NTxAnts',                 1, ...
            'NRxAnts',                 2, ...
            'DMRSAdditionalPosition',  1, ...
            'EnablePTRS',              false, ...
            'FRC',                     'G-FR2-A3-15', ...
            'SNR',                     -2.1 ...
        ), ...
        ... struct( ...
        ...     'Name',                    'TS38.104 V15.19.0 Table 11.2.2.1.2-3 Row 3', ...
        ...     'DelayProfile',            'TDLA30', ...
        ...     'MaximumDopplerShift',     300, ...
        ...     'NTxAnts',                 1, ...
        ...     'NRxAnts',                 2, ...
        ...     'DMRSAdditionalPosition',  0, ...
        ...     'EnablePTRS',              true, ...
        ...     'FRC',                     'G-FR2-A4-3', ...
        ...     'SNR',                     11.6 ...
        ... ), ...
        struct( ...
            'Name',                    'TS38.104 V15.19.0 Table 11.2.2.1.2-3 Row 4', ...
            'DelayProfile',            'TDLA30', ...
            'MaximumDopplerShift',     300, ...
            'NTxAnts',                 1, ...
            'NRxAnts',                 2, ...
            'DMRSAdditionalPosition',  0, ...
            'EnablePTRS',              false, ...
            'FRC',                     'G-FR2-A4-3', ...
            'SNR',                     10.9 ...
        ), ...
        ... struct( ...
        ...     'Name',                    'TS38.104 V15.19.0 Table 11.2.2.1.2-3 Row 5', ...
        ...     'DelayProfile',            'TDLA30', ...
        ...     'MaximumDopplerShift',     300, ...
        ...     'NTxAnts',                 1, ...
        ...     'NRxAnts',                 2, ...
        ...     'DMRSAdditionalPosition',  1, ...
        ...     'EnablePTRS',              true, ...
        ...     'FRC',                     'G-FR2-A4-13', ...
        ...     'SNR',                     10.9 ...
        ... ), ...
        struct( ...
            'Name',                    'TS38.104 V15.19.0 Table 11.2.2.1.2-3 Row 6', ...
            'DelayProfile',            'TDLA30', ...
            'MaximumDopplerShift',     300, ...
            'NTxAnts',                 1, ...
            'NRxAnts',                 2, ...
            'DMRSAdditionalPosition',  1, ...
            'EnablePTRS',              false, ...
            'FRC',                     'G-FR2-A4-13', ...
            'SNR',                     10.5 ...
        ), ...
        ... struct( ...
        ...     'Name',                    'TS38.104 V15.19.0 Table 11.2.2.1.2-3 Row 7', ...
        ...     'DelayProfile',            'TDLA30', ...
        ...     'MaximumDopplerShift',     75, ...
        ...     'NTxAnts',                 1, ...
        ...     'NRxAnts',                 2, ...
        ...     'DMRSAdditionalPosition',  0, ...
        ...     'EnablePTRS',              true, ...
        ...     'FRC',                     'G-FR2-A5-3', ...
        ...     'SNR',                     13.7 ...
        ... ), ...
        struct( ...
            'Name',                    'TS38.104 V15.19.0 Table 11.2.2.1.2-3 Row 8', ...
            'DelayProfile',            'TDLA30', ...
            'MaximumDopplerShift',     75, ...
            'NTxAnts',                 1, ...
            'NRxAnts',                 2, ...
            'DMRSAdditionalPosition',  0, ...
            'EnablePTRS',              false, ...
            'FRC',                     'G-FR2-A5-3', ...
            'SNR',                     13.1 ...
        ), ...
        ... struct( ...
        ...     'Name',                    'TS38.104 V15.19.0 Table 11.2.2.1.2-3 Row 9', ...
        ...     'DelayProfile',            'TDLA30', ...
        ...     'MaximumDopplerShift',     75, ...
        ...     'NTxAnts',                 1, ...
        ...     'NRxAnts',                 2, ...
        ...     'DMRSAdditionalPosition',  1, ...
        ...     'EnablePTRS',              true, ...
        ...     'FRC',                     'G-FR2-A5-8', ...
        ...     'SNR',                     13.2 ...
        ... ), ...
        struct( ...
            'Name',                    'TS38.104 V15.19.0 Table 11.2.2.1.2-3 Row 10', ...
            'DelayProfile',            'TDLA30', ...
            'MaximumDopplerShift',     75, ...
            'NTxAnts',                 1, ...
            'NRxAnts',                 2, ...
            'DMRSAdditionalPosition',  1, ...
            'EnablePTRS',              false, ...
            'FRC',                     'G-FR2-A5-8', ...
            'SNR',                     13.0 ...
        ), ...
        struct( ...
            'Name',                    'TS38.104 V15.19.0 Table 11.2.2.1.2-3 Row 11', ...
            'DelayProfile',            'TDLA30', ...
            'MaximumDopplerShift',     300, ...
            'NTxAnts',                 2, ...
            'NRxAnts',                 2, ...
            'DMRSAdditionalPosition',  0, ...
            'EnablePTRS',              false, ...
            'FRC',                     'G-FR2-A3-8', ...
            'SNR',                     1.4 ...
        ), ...
        struct( ...
            'Name',                    'TS38.104 V15.19.0 Table 11.2.2.1.2-3 Row 12', ...
            'DelayProfile',            'TDLA30', ...
            'MaximumDopplerShift',     300, ...
            'NTxAnts',                 2, ...
            'NRxAnts',                 2, ...
            'DMRSAdditionalPosition',  1, ...
            'EnablePTRS',              false, ...
            'FRC',                     'G-FR2-A3-20', ...
            'SNR',                     1.3 ...
        ), ...
        ... struct( ...
        ...     'Name',                    'TS38.104 V15.19.0 Table 11.2.2.1.2-3 Row 13', ...
        ...     'DelayProfile',            'TDLA30', ...
        ...     'MaximumDopplerShift',     300, ...
        ...     'NTxAnts',                 2, ...
        ...     'NRxAnts',                 2, ...
        ...     'DMRSAdditionalPosition',  0, ...
        ...     'EnablePTRS',              true, ...
        ...     'FRC',                     'G-FR2-A4-8', ...
        ...     'SNR',                     21.1 ...
        ... ), ...
        struct( ...
            'Name',                    'TS38.104 V15.19.0 Table 11.2.2.1.2-3 Row 14', ...
            'DelayProfile',            'TDLA30', ...
            'MaximumDopplerShift',     300, ...
            'NTxAnts',                 2, ...
            'NRxAnts',                 2, ...
            'DMRSAdditionalPosition',  0, ...
            'EnablePTRS',              false, ...
            'FRC',                     'G-FR2-A4-8', ...
            'SNR',                     18.6 ...
        ), ...
        struct( ...
            'Name',                    'TS38.104 V15.19.0 Table 11.2.2.1.2-3 Row 15', ...
            'DelayProfile',            'TDLA30', ...
            'MaximumDopplerShift',     300, ...
            'NTxAnts',                 2, ...
            'NRxAnts',                 2, ...
            'DMRSAdditionalPosition',  1, ...
            'EnablePTRS',              true, ...
            'FRC',                     'G-FR2-A4-18', ...
            'SNR',                     19.6 ...
        ), ...
        struct( ...
            'Name',                    'TS38.104 V15.19.0 Table 11.2.2.1.2-3 Row 16', ...
            'DelayProfile',            'TDLA30', ...
            'MaximumDopplerShift',     300, ...
            'NTxAnts',                 2, ...
            'NRxAnts',                 2, ...
            'DMRSAdditionalPosition',  1, ...
            'EnablePTRS',              false, ...
            'FRC',                     'G-FR2-A4-18', ...
            'SNR',                     17.6 ...
        ), ...
    };
end % of function TestConfig = createTestConfigTable11_2_2_1_2_3()
