// SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
// SPDX-License-Identifier: BSD-3-Clause-Open-MPI

#pragma once

// This file was generated using the following MATLAB class on 28-04-2026 (seed 0):
//   + "ocuduPDSCHEncoderUnittest.m"

#include "ocudu/phy/upper/codeblock_metadata.h"
#include "ocudu/support/file_vector.h"

namespace ocudu {

struct test_case_t {
  segmenter_config     config;
  file_vector<uint8_t> transport_block;
  file_vector<uint8_t> encoded;
};

static const std::vector<test_case_t> pdsch_encoder_test_data = {
    // clang-format off
  {{units::bytes{116}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input0.dat"}, {"test_data/pdsch_encoder_test_output0.dat"}},
  {{units::bytes{185}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input1.dat"}, {"test_data/pdsch_encoder_test_output1.dat"}},
  {{units::bytes{301}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input2.dat"}, {"test_data/pdsch_encoder_test_output2.dat"}},
  {{units::bytes{437}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input3.dat"}, {"test_data/pdsch_encoder_test_output3.dat"}},
  {{units::bytes{576}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QPSK, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input4.dat"}, {"test_data/pdsch_encoder_test_output4.dat"}},
  {{units::bytes{720}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input5.dat"}, {"test_data/pdsch_encoder_test_output5.dat"}},
  {{units::bytes{816}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input6.dat"}, {"test_data/pdsch_encoder_test_output6.dat"}},
  {{units::bytes{928}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input7.dat"}, {"test_data/pdsch_encoder_test_output7.dat"}},
  {{units::bytes{1057}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input8.dat"}, {"test_data/pdsch_encoder_test_output8.dat"}},
  {{units::bytes{1185}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input9.dat"}, {"test_data/pdsch_encoder_test_output9.dat"}},
  {{units::bytes{1249}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input10.dat"}, {"test_data/pdsch_encoder_test_output10.dat"}},
  {{units::bytes{1345}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input11.dat"}, {"test_data/pdsch_encoder_test_output11.dat"}},
  {{units::bytes{1473}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input12.dat"}, {"test_data/pdsch_encoder_test_output12.dat"}},
  {{units::bytes{1633}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input13.dat"}, {"test_data/pdsch_encoder_test_output13.dat"}},
  {{units::bytes{1761}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input14.dat"}, {"test_data/pdsch_encoder_test_output14.dat"}},
  {{units::bytes{1889}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input15.dat"}, {"test_data/pdsch_encoder_test_output15.dat"}},
  {{units::bytes{2049}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input16.dat"}, {"test_data/pdsch_encoder_test_output16.dat"}},
  {{units::bytes{2178}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input17.dat"}, {"test_data/pdsch_encoder_test_output17.dat"}},
  {{units::bytes{2370}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input18.dat"}, {"test_data/pdsch_encoder_test_output18.dat"}},
  {{units::bytes{2496}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input19.dat"}, {"test_data/pdsch_encoder_test_output19.dat"}},
  {{units::bytes{2625}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input20.dat"}, {"test_data/pdsch_encoder_test_output20.dat"}},
  {{units::bytes{2688}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input21.dat"}, {"test_data/pdsch_encoder_test_output21.dat"}},
  {{units::bytes{2880}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input22.dat"}, {"test_data/pdsch_encoder_test_output22.dat"}},
  {{units::bytes{3009}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input23.dat"}, {"test_data/pdsch_encoder_test_output23.dat"}},
  {{units::bytes{3201}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input24.dat"}, {"test_data/pdsch_encoder_test_output24.dat"}},
  {{units::bytes{3393}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input25.dat"}, {"test_data/pdsch_encoder_test_output25.dat"}},
  {{units::bytes{3457}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input26.dat"}, {"test_data/pdsch_encoder_test_output26.dat"}},
  {{units::bytes{3585}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3900}, {"test_data/pdsch_encoder_test_input27.dat"}, {"test_data/pdsch_encoder_test_output27.dat"}},
  {{units::bytes{22}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 780}, {"test_data/pdsch_encoder_test_input28.dat"}, {"test_data/pdsch_encoder_test_output28.dat"}},
  {{units::bytes{88}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 1872}, {"test_data/pdsch_encoder_test_input29.dat"}, {"test_data/pdsch_encoder_test_output29.dat"}},
  {{units::bytes{193}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 2496}, {"test_data/pdsch_encoder_test_input30.dat"}, {"test_data/pdsch_encoder_test_output30.dat"}},
  {{units::bytes{388}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 3432}, {"test_data/pdsch_encoder_test_input31.dat"}, {"test_data/pdsch_encoder_test_output31.dat"}},
  {{units::bytes{341}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 2340}, {"test_data/pdsch_encoder_test_input32.dat"}, {"test_data/pdsch_encoder_test_output32.dat"}},
  {{units::bytes{317}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QAM16, 0, 1, 1716}, {"test_data/pdsch_encoder_test_input33.dat"}, {"test_data/pdsch_encoder_test_output33.dat"}},
  {{units::bytes{469}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QAM16, 0, 1, 2184}, {"test_data/pdsch_encoder_test_input34.dat"}, {"test_data/pdsch_encoder_test_output34.dat"}},
  {{units::bytes{421}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QAM16, 0, 1, 1716}, {"test_data/pdsch_encoder_test_input35.dat"}, {"test_data/pdsch_encoder_test_output35.dat"}},
  {{units::bytes{592}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 2184}, {"test_data/pdsch_encoder_test_input36.dat"}, {"test_data/pdsch_encoder_test_output36.dat"}},
  {{units::bytes{656}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 2184}, {"test_data/pdsch_encoder_test_input37.dat"}, {"test_data/pdsch_encoder_test_output37.dat"}},
  {{units::bytes{704}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 2184}, {"test_data/pdsch_encoder_test_input38.dat"}, {"test_data/pdsch_encoder_test_output38.dat"}},
  {{units::bytes{1057}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3120}, {"test_data/pdsch_encoder_test_input39.dat"}, {"test_data/pdsch_encoder_test_output39.dat"}},
  {{units::bytes{880}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 2340}, {"test_data/pdsch_encoder_test_input40.dat"}, {"test_data/pdsch_encoder_test_output40.dat"}},
  {{units::bytes{1153}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 2808}, {"test_data/pdsch_encoder_test_input41.dat"}, {"test_data/pdsch_encoder_test_output41.dat"}},
  {{units::bytes{217}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QAM64, 0, 1, 468}, {"test_data/pdsch_encoder_test_input42.dat"}, {"test_data/pdsch_encoder_test_output42.dat"}},
  {{units::bytes{688}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 1404}, {"test_data/pdsch_encoder_test_input43.dat"}, {"test_data/pdsch_encoder_test_output43.dat"}},
  {{units::bytes{656}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 1248}, {"test_data/pdsch_encoder_test_input44.dat"}, {"test_data/pdsch_encoder_test_output44.dat"}},
  {{units::bytes{1601}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 2808}, {"test_data/pdsch_encoder_test_input45.dat"}, {"test_data/pdsch_encoder_test_output45.dat"}},
  {{units::bytes{1121}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 1872}, {"test_data/pdsch_encoder_test_input46.dat"}, {"test_data/pdsch_encoder_test_output46.dat"}},
  {{units::bytes{1793}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 2808}, {"test_data/pdsch_encoder_test_input47.dat"}, {"test_data/pdsch_encoder_test_output47.dat"}},
  {{units::bytes{1345}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 2028}, {"test_data/pdsch_encoder_test_input48.dat"}, {"test_data/pdsch_encoder_test_output48.dat"}},
  {{units::bytes{1505}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 2184}, {"test_data/pdsch_encoder_test_input49.dat"}, {"test_data/pdsch_encoder_test_output49.dat"}},
  {{units::bytes{1153}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 1560}, {"test_data/pdsch_encoder_test_input50.dat"}, {"test_data/pdsch_encoder_test_output50.dat"}},
  {{units::bytes{608}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 780}, {"test_data/pdsch_encoder_test_input51.dat"}, {"test_data/pdsch_encoder_test_output51.dat"}},
  {{units::bytes{1921}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 2340}, {"test_data/pdsch_encoder_test_input52.dat"}, {"test_data/pdsch_encoder_test_output52.dat"}},
  {{units::bytes{2017}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 2340}, {"test_data/pdsch_encoder_test_input53.dat"}, {"test_data/pdsch_encoder_test_output53.dat"}},
  {{units::bytes{1665}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 1872}, {"test_data/pdsch_encoder_test_input54.dat"}, {"test_data/pdsch_encoder_test_output54.dat"}},
  {{units::bytes{2625}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 2808}, {"test_data/pdsch_encoder_test_input55.dat"}, {"test_data/pdsch_encoder_test_output55.dat"}},
  {{units::bytes{106}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input56.dat"}, {"test_data/pdsch_encoder_test_output56.dat"}},
  {{units::bytes{169}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input57.dat"}, {"test_data/pdsch_encoder_test_output57.dat"}},
  {{units::bytes{269}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input58.dat"}, {"test_data/pdsch_encoder_test_output58.dat"}},
  {{units::bytes{405}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input59.dat"}, {"test_data/pdsch_encoder_test_output59.dat"}},
  {{units::bytes{528}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QPSK, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input60.dat"}, {"test_data/pdsch_encoder_test_output60.dat"}},
  {{units::bytes{656}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input61.dat"}, {"test_data/pdsch_encoder_test_output61.dat"}},
  {{units::bytes{752}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input62.dat"}, {"test_data/pdsch_encoder_test_output62.dat"}},
  {{units::bytes{864}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input63.dat"}, {"test_data/pdsch_encoder_test_output63.dat"}},
  {{units::bytes{976}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input64.dat"}, {"test_data/pdsch_encoder_test_output64.dat"}},
  {{units::bytes{1089}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input65.dat"}, {"test_data/pdsch_encoder_test_output65.dat"}},
  {{units::bytes{1153}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input66.dat"}, {"test_data/pdsch_encoder_test_output66.dat"}},
  {{units::bytes{1217}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input67.dat"}, {"test_data/pdsch_encoder_test_output67.dat"}},
  {{units::bytes{1377}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input68.dat"}, {"test_data/pdsch_encoder_test_output68.dat"}},
  {{units::bytes{1505}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input69.dat"}, {"test_data/pdsch_encoder_test_output69.dat"}},
  {{units::bytes{1633}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input70.dat"}, {"test_data/pdsch_encoder_test_output70.dat"}},
  {{units::bytes{1761}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input71.dat"}, {"test_data/pdsch_encoder_test_output71.dat"}},
  {{units::bytes{1889}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input72.dat"}, {"test_data/pdsch_encoder_test_output72.dat"}},
  {{units::bytes{2049}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input73.dat"}, {"test_data/pdsch_encoder_test_output73.dat"}},
  {{units::bytes{2178}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input74.dat"}, {"test_data/pdsch_encoder_test_output74.dat"}},
  {{units::bytes{2304}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input75.dat"}, {"test_data/pdsch_encoder_test_output75.dat"}},
  {{units::bytes{2370}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input76.dat"}, {"test_data/pdsch_encoder_test_output76.dat"}},
  {{units::bytes{2496}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input77.dat"}, {"test_data/pdsch_encoder_test_output77.dat"}},
  {{units::bytes{2625}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input78.dat"}, {"test_data/pdsch_encoder_test_output78.dat"}},
  {{units::bytes{2817}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input79.dat"}, {"test_data/pdsch_encoder_test_output79.dat"}},
  {{units::bytes{2946}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input80.dat"}, {"test_data/pdsch_encoder_test_output80.dat"}},
  {{units::bytes{3138}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input81.dat"}, {"test_data/pdsch_encoder_test_output81.dat"}},
  {{units::bytes{3201}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input82.dat"}, {"test_data/pdsch_encoder_test_output82.dat"}},
  {{units::bytes{3329}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3600}, {"test_data/pdsch_encoder_test_input83.dat"}, {"test_data/pdsch_encoder_test_output83.dat"}},
  {{units::bytes{38}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 1296}, {"test_data/pdsch_encoder_test_input84.dat"}, {"test_data/pdsch_encoder_test_output84.dat"}},
  {{units::bytes{88}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 1872}, {"test_data/pdsch_encoder_test_input85.dat"}, {"test_data/pdsch_encoder_test_output85.dat"}},
  {{units::bytes{177}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 2304}, {"test_data/pdsch_encoder_test_input86.dat"}, {"test_data/pdsch_encoder_test_output86.dat"}},
  {{units::bytes{63}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 576}, {"test_data/pdsch_encoder_test_input87.dat"}, {"test_data/pdsch_encoder_test_output87.dat"}},
  {{units::bytes{217}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 1440}, {"test_data/pdsch_encoder_test_input88.dat"}, {"test_data/pdsch_encoder_test_output88.dat"}},
  {{units::bytes{301}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QAM16, 0, 1, 1584}, {"test_data/pdsch_encoder_test_input89.dat"}, {"test_data/pdsch_encoder_test_output89.dat"}},
  {{units::bytes{469}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QAM16, 0, 1, 2160}, {"test_data/pdsch_encoder_test_input90.dat"}, {"test_data/pdsch_encoder_test_output90.dat"}},
  {{units::bytes{784}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 3312}, {"test_data/pdsch_encoder_test_input91.dat"}, {"test_data/pdsch_encoder_test_output91.dat"}},
  {{units::bytes{544}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 2016}, {"test_data/pdsch_encoder_test_input92.dat"}, {"test_data/pdsch_encoder_test_output92.dat"}},
  {{units::bytes{688}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 2304}, {"test_data/pdsch_encoder_test_input93.dat"}, {"test_data/pdsch_encoder_test_output93.dat"}},
  {{units::bytes{688}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 2160}, {"test_data/pdsch_encoder_test_input94.dat"}, {"test_data/pdsch_encoder_test_output94.dat"}},
  {{units::bytes{592}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 1728}, {"test_data/pdsch_encoder_test_input95.dat"}, {"test_data/pdsch_encoder_test_output95.dat"}},
  {{units::bytes{976}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 2592}, {"test_data/pdsch_encoder_test_input96.dat"}, {"test_data/pdsch_encoder_test_output96.dat"}},
  {{units::bytes{1089}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 2592}, {"test_data/pdsch_encoder_test_input97.dat"}, {"test_data/pdsch_encoder_test_output97.dat"}},
  {{units::bytes{640}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 1440}, {"test_data/pdsch_encoder_test_input98.dat"}, {"test_data/pdsch_encoder_test_output98.dat"}},
  {{units::bytes{704}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 1440}, {"test_data/pdsch_encoder_test_input99.dat"}, {"test_data/pdsch_encoder_test_output99.dat"}},
  {{units::bytes{1057}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 2016}, {"test_data/pdsch_encoder_test_input100.dat"}, {"test_data/pdsch_encoder_test_output100.dat"}},
  {{units::bytes{976}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 1728}, {"test_data/pdsch_encoder_test_input101.dat"}, {"test_data/pdsch_encoder_test_output101.dat"}},
  {{units::bytes{1024}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 1728}, {"test_data/pdsch_encoder_test_input102.dat"}, {"test_data/pdsch_encoder_test_output102.dat"}},
  {{units::bytes{1665}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 2592}, {"test_data/pdsch_encoder_test_input103.dat"}, {"test_data/pdsch_encoder_test_output103.dat"}},
  {{units::bytes{2112}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3168}, {"test_data/pdsch_encoder_test_input104.dat"}, {"test_data/pdsch_encoder_test_output104.dat"}},
  {{units::bytes{405}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 576}, {"test_data/pdsch_encoder_test_input105.dat"}, {"test_data/pdsch_encoder_test_output105.dat"}},
  {{units::bytes{1601}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 2160}, {"test_data/pdsch_encoder_test_input106.dat"}, {"test_data/pdsch_encoder_test_output106.dat"}},
  {{units::bytes{1008}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 1296}, {"test_data/pdsch_encoder_test_input107.dat"}, {"test_data/pdsch_encoder_test_output107.dat"}},
  {{units::bytes{1057}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 1296}, {"test_data/pdsch_encoder_test_input108.dat"}, {"test_data/pdsch_encoder_test_output108.dat"}},
  {{units::bytes{1601}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 1872}, {"test_data/pdsch_encoder_test_input109.dat"}, {"test_data/pdsch_encoder_test_output109.dat"}},
  {{units::bytes{2304}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 2592}, {"test_data/pdsch_encoder_test_input110.dat"}, {"test_data/pdsch_encoder_test_output110.dat"}},
  {{units::bytes{656}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 720}, {"test_data/pdsch_encoder_test_input111.dat"}, {"test_data/pdsch_encoder_test_output111.dat"}},
  {{units::bytes{96}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input112.dat"}, {"test_data/pdsch_encoder_test_output112.dat"}},
  {{units::bytes{157}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input113.dat"}, {"test_data/pdsch_encoder_test_output113.dat"}},
  {{units::bytes{253}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input114.dat"}, {"test_data/pdsch_encoder_test_output114.dat"}},
  {{units::bytes{372}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input115.dat"}, {"test_data/pdsch_encoder_test_output115.dat"}},
  {{units::bytes{480}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QPSK, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input116.dat"}, {"test_data/pdsch_encoder_test_output116.dat"}},
  {{units::bytes{608}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input117.dat"}, {"test_data/pdsch_encoder_test_output117.dat"}},
  {{units::bytes{704}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input118.dat"}, {"test_data/pdsch_encoder_test_output118.dat"}},
  {{units::bytes{784}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input119.dat"}, {"test_data/pdsch_encoder_test_output119.dat"}},
  {{units::bytes{896}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input120.dat"}, {"test_data/pdsch_encoder_test_output120.dat"}},
  {{units::bytes{992}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input121.dat"}, {"test_data/pdsch_encoder_test_output121.dat"}},
  {{units::bytes{1057}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input122.dat"}, {"test_data/pdsch_encoder_test_output122.dat"}},
  {{units::bytes{1121}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input123.dat"}, {"test_data/pdsch_encoder_test_output123.dat"}},
  {{units::bytes{1249}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input124.dat"}, {"test_data/pdsch_encoder_test_output124.dat"}},
  {{units::bytes{1377}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input125.dat"}, {"test_data/pdsch_encoder_test_output125.dat"}},
  {{units::bytes{1473}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input126.dat"}, {"test_data/pdsch_encoder_test_output126.dat"}},
  {{units::bytes{1601}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input127.dat"}, {"test_data/pdsch_encoder_test_output127.dat"}},
  {{units::bytes{1729}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input128.dat"}, {"test_data/pdsch_encoder_test_output128.dat"}},
  {{units::bytes{1857}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input129.dat"}, {"test_data/pdsch_encoder_test_output129.dat"}},
  {{units::bytes{1985}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input130.dat"}, {"test_data/pdsch_encoder_test_output130.dat"}},
  {{units::bytes{2112}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input131.dat"}, {"test_data/pdsch_encoder_test_output131.dat"}},
  {{units::bytes{2178}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input132.dat"}, {"test_data/pdsch_encoder_test_output132.dat"}},
  {{units::bytes{2304}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input133.dat"}, {"test_data/pdsch_encoder_test_output133.dat"}},
  {{units::bytes{2433}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input134.dat"}, {"test_data/pdsch_encoder_test_output134.dat"}},
  {{units::bytes{2562}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input135.dat"}, {"test_data/pdsch_encoder_test_output135.dat"}},
  {{units::bytes{2688}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input136.dat"}, {"test_data/pdsch_encoder_test_output136.dat"}},
  {{units::bytes{2880}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input137.dat"}, {"test_data/pdsch_encoder_test_output137.dat"}},
  {{units::bytes{2946}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input138.dat"}, {"test_data/pdsch_encoder_test_output138.dat"}},
  {{units::bytes{3072}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input139.dat"}, {"test_data/pdsch_encoder_test_output139.dat"}},
  {{units::bytes{80}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 2640}, {"test_data/pdsch_encoder_test_input140.dat"}, {"test_data/pdsch_encoder_test_output140.dat"}},
  {{units::bytes{157}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 3300}, {"test_data/pdsch_encoder_test_input141.dat"}, {"test_data/pdsch_encoder_test_output141.dat"}},
  {{units::bytes{123}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 1584}, {"test_data/pdsch_encoder_test_input142.dat"}, {"test_data/pdsch_encoder_test_output142.dat"}},
  {{units::bytes{209}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 1848}, {"test_data/pdsch_encoder_test_input143.dat"}, {"test_data/pdsch_encoder_test_output143.dat"}},
  {{units::bytes{157}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QPSK, 0, 1, 1056}, {"test_data/pdsch_encoder_test_input144.dat"}, {"test_data/pdsch_encoder_test_output144.dat"}},
  {{units::bytes{201}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QAM16, 0, 1, 1056}, {"test_data/pdsch_encoder_test_input145.dat"}, {"test_data/pdsch_encoder_test_output145.dat"}},
  {{units::bytes{169}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QAM16, 0, 1, 792}, {"test_data/pdsch_encoder_test_input146.dat"}, {"test_data/pdsch_encoder_test_output146.dat"}},
  {{units::bytes{560}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 2376}, {"test_data/pdsch_encoder_test_input147.dat"}, {"test_data/pdsch_encoder_test_output147.dat"}},
  {{units::bytes{496}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 1848}, {"test_data/pdsch_encoder_test_input148.dat"}, {"test_data/pdsch_encoder_test_output148.dat"}},
  {{units::bytes{357}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QAM16, 0, 1, 1188}, {"test_data/pdsch_encoder_test_input149.dat"}, {"test_data/pdsch_encoder_test_output149.dat"}},
  {{units::bytes{768}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM16, 0, 1, 2376}, {"test_data/pdsch_encoder_test_input150.dat"}, {"test_data/pdsch_encoder_test_output150.dat"}},
  {{units::bytes{672}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 1980}, {"test_data/pdsch_encoder_test_input151.dat"}, {"test_data/pdsch_encoder_test_output151.dat"}},
  {{units::bytes{592}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 1584}, {"test_data/pdsch_encoder_test_input152.dat"}, {"test_data/pdsch_encoder_test_output152.dat"}},
  {{units::bytes{592}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 1452}, {"test_data/pdsch_encoder_test_input153.dat"}, {"test_data/pdsch_encoder_test_output153.dat"}},
  {{units::bytes{896}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 1980}, {"test_data/pdsch_encoder_test_input154.dat"}, {"test_data/pdsch_encoder_test_output154.dat"}},
  {{units::bytes{325}, ldpc_base_graph_type::BG2, 0, modulation_scheme::QAM64, 0, 1, 660}, {"test_data/pdsch_encoder_test_input155.dat"}, {"test_data/pdsch_encoder_test_output155.dat"}},
  {{units::bytes{1537}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 2904}, {"test_data/pdsch_encoder_test_input156.dat"}, {"test_data/pdsch_encoder_test_output156.dat"}},
  {{units::bytes{1057}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 1848}, {"test_data/pdsch_encoder_test_input157.dat"}, {"test_data/pdsch_encoder_test_output157.dat"}},
  {{units::bytes{1024}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 1716}, {"test_data/pdsch_encoder_test_input158.dat"}, {"test_data/pdsch_encoder_test_output158.dat"}},
  {{units::bytes{1089}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM64, 0, 1, 1716}, {"test_data/pdsch_encoder_test_input159.dat"}, {"test_data/pdsch_encoder_test_output159.dat"}},
  {{units::bytes{1153}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 1716}, {"test_data/pdsch_encoder_test_input160.dat"}, {"test_data/pdsch_encoder_test_output160.dat"}},
  {{units::bytes{1377}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 1980}, {"test_data/pdsch_encoder_test_input161.dat"}, {"test_data/pdsch_encoder_test_output161.dat"}},
  {{units::bytes{1153}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 1584}, {"test_data/pdsch_encoder_test_input162.dat"}, {"test_data/pdsch_encoder_test_output162.dat"}},
  {{units::bytes{2178}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 2772}, {"test_data/pdsch_encoder_test_input163.dat"}, {"test_data/pdsch_encoder_test_output163.dat"}},
  {{units::bytes{976}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 1188}, {"test_data/pdsch_encoder_test_input164.dat"}, {"test_data/pdsch_encoder_test_output164.dat"}},
  {{units::bytes{912}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 1056}, {"test_data/pdsch_encoder_test_input165.dat"}, {"test_data/pdsch_encoder_test_output165.dat"}},
  {{units::bytes{1761}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 1980}, {"test_data/pdsch_encoder_test_input166.dat"}, {"test_data/pdsch_encoder_test_output166.dat"}},
  {{units::bytes{2562}, ldpc_base_graph_type::BG1, 0, modulation_scheme::QAM256, 0, 1, 2772}, {"test_data/pdsch_encoder_test_input167.dat"}, {"test_data/pdsch_encoder_test_output167.dat"}},
    // clang-format on
};

} // namespace ocudu
