%ocuduPUCCHAnalyzer Analyzes a PUCCH transmission from a resource grid.
%   ocuduPUCCHAnalyzer(CARRIER, PUCCH, EXTRA, RGFILENAME, RGOFFSET, RGSIZE) analyzes the
%   NR Physical Uplink Control Channel transmission detailed by the carrier
%   configuration CARRIER and by the control channel configuration PUCCH. The
%   structure EXTRA specifies the number of bits in the UCI message (i.e., NumHARQAck,
%   NumSR, NumCSIPart1, NumCSIPart2). The resource grid IQ samples are stored in the
%   binary file RGFILENAME. RGOFFSET and RGSIZE are the offset and size, as
%   a number of single-precision complex floating point numbers, of the slot
%   containing the PUCCH transmission inside the binary file.
%
%   Example:
%   % The relevant data can be found in the log file generated by the OCUDU gNB:
%   % look for lines like the following
%   %    2023-06-07T20:54:24.502414 [Upper PHY] [I] [  584.19] RX_SYMBOL: sector=0 offset=636504 size=45864
%   %    2023-06-07T20:54:24.502277 [UL-PHY2 ] [D] [  584.19] PUCCH: rnti=0x4601 format=1 ...
%
%   % Use ocuduParseLogs to populate the carrier and PUCCH configuration objects
%   % as well as the extra structure (you will be asked to select the PUCCH entry of the logs):
%   [carrier, pucch, extra] = ocuduParseLogs
%
%   % Launch the analyzer
%   ocuduPUCCHAnalyzer(carrier, pucch, extra, 'rx_symbols.bin', 636504, 45864)
%
%   See also ocuduParseLogs.

% SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
% SPDX-License-Identifier: BSD-3-Clause-Open-MPI

function ocuduPUCCHAnalyzer(carrier, pucch, extra, rgFilename, rgOffset, rgSize)
    arguments
        carrier    (1, 1) nrCarrierConfig
        pucch      (1, 1) {mustBeA(pucch, ["nrPUCCH0Config", "nrPUCCH1Config", "nrPUCCH2Config", "nrPUCCH3Config", "nrPUCCH4Config"])}
        extra      (1, 1) struct
        rgFilename (1, :) char {mustBeFile}
        rgOffset   (1, 1) double {mustBeInteger, mustBePositive}
        rgSize     (1, 1) double {mustBeInteger, mustBePositive}
    end

    nSubcarriers = carrier.NSizeGrid * 12;
    nSymbols = 14;
    nPorts = floor(rgSize / (nSubcarriers * nSymbols));

    assert(nSubcarriers * nSymbols * nPorts == rgSize, ['The dimensions of the resource grid ', ...
        '(%d x %d) are not consistent with the buffer size %d.'], nSubcarriers, nSymbols, rgSize);

    % Read file containing the resource grid.
    rxGrid = reshape(ocuduTest.helpers.readComplexFloatFile(rgFilename, rgOffset, rgSize), ...
        [nSubcarriers, nSymbols, nPorts]);

    dmrsInd = nrPUCCHDMRSIndices(carrier, pucch);
    dmrsSym = nrPUCCHDMRS(carrier, pucch);

    [estChannel, noiseEst] = nrChannelEstimate(carrier, rxGrid, dmrsInd, dmrsSym);

    % Get PUCCH REs from received grid and estimated channel grid.
    pucchIndices = nrPUCCHIndices(carrier, pucch);
    [pucchRx, pucchHest] = nrExtractResources(pucchIndices, rxGrid, estChannel);

    % Perform equalization.
    pucchEq = nrEqualizeMMSE(pucchRx, pucchHest, noiseEst);

    % Decode PUCCH symbols
    if isa(pucch, 'nrPUCCH0Config')
        if (extra.NumSR == 1)
            ouci = [extra.NumHARQAck; extra.NumSR];
        else
            ouci = extra.NumHARQAck;
        end
        pucchEq = pucchRx;
    elseif isa(pucch, 'nrPUCCH1Config')
        % If there are no ACK bits, we still need to check for SR.
        ouci = max(extra.NumHARQAck, 1);
    else
        ouci = extra.NumHARQAck + extra.NumSR + extra.NumCSIPart1 + extra.NumCSIPart2;
    end

    [uciLLRs, rxSymbols, metric] = nrPUCCHDecode(carrier, pucch, ouci, pucchEq, noiseEst);

    if (isa(pucch, 'nrPUCCH0Config') || isa(pucch, 'nrPUCCH1Config'))
        % For F0 and F1, nrPUCCHDecode returns hard (as opposed to soft) bits.
        fprintf('Received ACK bits:\n');
        disp(uciLLRs{1});
        if (numel(uciLLRs) == 2)
            fprintf('Received SR bit:\n');
            disp(uciLLRs{2});
        end
    else
        fprintf('Received LLRs:\n');
        disp(uciLLRs{1});

        uciBits = nrUCIDecode(uciLLRs{1}, ouci);
        fprintf('Received bits:\n');
        disp(uciBits);
    end
    fprintf('Received constellation symbols:\n');
    disp(rxSymbols);
    fprintf('Detection metric (if applicable):\n');
    disp(metric);

    % Plots.
    figRG = figure("Name", "ocuduPUCCHAnalyzer: Resource grid amplitude");
    tiledlayout(nPorts, 1);
    figChannel = figure("Name", "ocuduPUCCHAnalyzer: Channel estimate");
    tiledlayout(nPorts, 2);

    for iPort=1:nPorts
        % Plot resource grid power.
        figure(figRG)
        nexttile
        imagesc(0, 0, abs(rxGrid(:, :, iPort)));
        % By default, imagesc reverses the y axis.
        set(gca, 'YDir','normal');
        colorbar;
        xlabel('Symbol')
        ylabel('Subcarrier')

        % Plot estimated channel magnitude.
        figure(figChannel)
        nexttile
        [symbolIndices, subcIndices] = meshgrid(0:nSymbols - 1, 0:nSubcarriers - 1);
        surf(symbolIndices, subcIndices, abs(estChannel(:, :, iPort)), 'LineStyle','none', 'FaceColor','flat');
        shading flat;
        colorbar;
        xlabel('Symbol');
        ylabel('Subcarrier');
        zlabel('Magnitude');
        zmin = min(abs(estChannel(:,:,iPort)), [], 'all');
        zmax = max(abs(estChannel(:,:,iPort)), [], 'all');
        if zmin == zmax
            zmin = zmin - 0.5;
            zmax = zmax + 0.5;
        else
            zmin = zmin * 0.9;
            zmax = zmax * 1.1;
        end
        axis([0, nSymbols - 1, 0, nSubcarriers - 1, zmin, zmax]);

        % Plot estimated channel phase.
        nexttile
        surf(symbolIndices, subcIndices, angle(estChannel(:, :, iPort)), 'LineStyle','none', 'FaceColor','flat');
        shading flat;
        colorbar;
        xlabel('Symbol');
        ylabel('Subcarrier');
        zlabel('Angle [rad]');
        zmin = min(angle(estChannel(:,:,iPort)), [], 'all');
        zmax = max(angle(estChannel(:,:,iPort)), [], 'all');
        if zmin == zmax
            zmin = zmin - 0.5;
            zmax = zmax + 0.5;
        else
            zmin = zmin * 0.9;
            zmax = zmax * 1.1;
        end
        axis([0, nSymbols - 1, 0, nSubcarriers - 1, zmin, zmax]);
    end

    figure
    tiledlayout('flow')
    % Plot detected constellation.
    nexttile
    if isa(pucch, 'nrPUCCH0Config')
        plot(real(pucchRx(:)), imag(pucchRx(:)), 'x');
        title('ocuduPUCCHAnalyzer: Received symbols');
    else
        plot(real(rxSymbols), imag(rxSymbols), 'x');
        title('ocuduPUCCHAnalyzer: Equalized constellation');
        axis([-1.2, 1.2, -1.2, 1.2])
    end
    grid on;
    xlabel('Real');
    ylabel('Imaginary');

    if (~isa(pucch, 'nrPUCCH1Config') && ~isa(pucch, 'nrPUCCH0Config'))
        % Plot soft bits histogram.
        nexttile
        histogram(uciLLRs{1}, 'Normalization', 'pdf');
        grid on;
        xlabel('Soft bits');
        ylabel('Soft bit count');
        title('Received soft bit distribution');
    end
