%listOCUDUblocks Provide a list of all tested OCUDU blocks.
%   BLOCKS = listOCUDUblocks returns a cell array with the names of all OCUDU blocks
%   with a unit test in the main folder.
%
%   BLOCKS = listOCUDUblocks('name') is the same as above.
%
%   BLOCKS = listOCUDUblocks('full') prepends each block name with the block path
%   relative the the OCUDU root folder.
%
%   BLOCKS = listOCUDUblocks('path') only returns a list of the paths (relative to
%   the OCUDU root folder) where the tested blocks are located.

%
%   Copyright 2021-2025 Software Radio Systems Limited
%
%   By using this file, you agree to the terms and conditions set
%   forth in the LICENSE file which can be found at the top level of
%   the distribution.
%

function blocks = listOCUDUblocks(format)
    arguments
        format (1,:) char {mustBeMember(format, {'name', 'path', 'full'})} = 'name'
    end

    blockDetails = {...
        'channel_equalizer', 'phy/upper/equalization/'; ...
        'demodulation_mapper', 'phy/upper/channel_modulation/'; ...
        'dft_processor', 'phy/generic_functions/'; ...
        'dmrs_pbch_processor', 'phy/upper/signal_processors/ssb/'; ...
        'dmrs_pdcch_processor', 'phy/upper/signal_processors/pdcch/'; ...
        'dmrs_pdsch_processor', 'phy/upper/signal_processors/pdsch/'; ...
        'dmrs_pucch_estimator', 'phy/upper/signal_processors/pucch/'; ...
        'dmrs_pusch_estimator', 'phy/upper/signal_processors/pusch/'; ...
        'ldpc_encoder', 'phy/upper/channel_coding/ldpc/'; ...
        'ldpc_rate_matcher', 'phy/upper/channel_coding/ldpc/'; ...
        'ldpc_segmenter', 'phy/upper/channel_coding/ldpc/'; ...
        'low_papr_sequence_generator', 'phy/upper/sequence_generators/'; ...
        'modulation_mapper', 'phy/upper/channel_modulation/'; ...
        'nzp_csi_rs_generator', 'phy/upper/signal_processors/nzp_csi_rs/'; ...
        'ofdm_demodulator', 'phy/lower/modulation/'; ...
        'ofdm_modulator', 'phy/lower/modulation/'; ...
        'ofdm_prach_demodulator', 'phy/lower/modulation/'; ...
        'ofh_compression', 'ofh/compression/'; ...
        'pbch_encoder', 'phy/upper/channel_processors/ssb/'; ...
        'pbch_modulator', 'phy/upper/channel_processors/ssb/'; ...
        'pdcch_candidates_common', 'ran/pdcch/'; ...
        'pdcch_candidates_ue', 'ran/pdcch/'; ...
        'pdcch_encoder', 'phy/upper/channel_processors/pdcch/'; ...
        'pdcch_modulator', 'phy/upper/channel_processors/pdcch/'; ...
        'pdcch_processor', 'phy/upper/channel_processors/pdcch/'; ...
        'pdsch_encoder', 'phy/upper/channel_processors/pdsch/'; ...
        'pdsch_modulator', 'phy/upper/channel_processors/pdsch/'; ...
        'pdsch_processor', 'phy/upper/channel_processors/pdsch/'; ...
        'port_channel_estimator', 'phy/upper/signal_processors/channel_estimator/'; ...
        'prach_configuration', 'ran/prach/'; ...
        'prach_detector', 'phy/upper/channel_processors/'; ...
        'prach_generator', 'phy/upper/channel_processors/'; ...
        'prach_scheduler', 'scheduler/common_scheduling/'; ...
        'prs_generator', 'phy/upper/signal_processors/prs/'; ...
        'ptrs_pdsch_generator', 'phy/upper/signal_processors/ptrs/'; ...
        'pucch_demodulator_format2', 'phy/upper/channel_processors/pucch/'; ...
        'pucch_demodulator_format3', 'phy/upper/channel_processors/pucch/'; ...
        'pucch_demodulator_format4', 'phy/upper/channel_processors/pucch/'; ...
        'pucch_processor_format0', 'phy/upper/channel_processors/pucch/'; ...
        'pucch_processor_format1', 'phy/upper/channel_processors/pucch/'; ...
        'pucch_processor_format2', 'phy/upper/channel_processors/pucch/'; ...
        'pucch_processor_format3', 'phy/upper/channel_processors/pucch/'; ...
        'pucch_processor_format4', 'phy/upper/channel_processors/pucch/'; ...
        'pusch_decoder', 'phy/upper/channel_processors/pusch/'; ...
        'pusch_demodulator', 'phy/upper/channel_processors/pusch/'; ...
        'pusch_processor', 'phy/upper/channel_processors/pusch/'; ...
        'pusch_tpmi_select', 'ran/pusch/'; ...
        'short_block_detector', 'phy/upper/channel_coding/short/'; ...
        'short_block_encoder', 'phy/upper/channel_coding/short/'; ...
        'srs_estimator', 'phy/upper/signal_processors/srs/'; ... 
        'ssb_processor', 'phy/upper/channel_processors/ssb/'; ...
        'tbs_calculator', 'ran/sch/'; ...
        'transform_precoder', 'phy/generic_functions/transform_precoding/'; ...
        'uci_decoder', 'phy/upper/channel_processors/uci/'; ...
        'ulsch_demultiplex', 'phy/upper/channel_processors/pusch/'; ...
        'ulsch_info', 'ran/pusch/'; ...
        };

    switch format
        case 'name'
            blocks = blockDetails(:, 1).';
        case 'path'
            blocks = unique(blockDetails(:, 2).');
        case 'full'
            blocks = strcat(blockDetails(:, 2), blockDetails(:, 1)).';
    end
end
