stages:
  - build testvectors
  - run unit tests

build testvectors:
  stage: build testvectors
  variables:
    GIT_STRATEGY: clone
  tags:
    - matlab
  artifacts:
    paths:
      - artifacts/
  script:
    - mkdir -p ./artifacts
    - export ARTIFACTSDIR="`pwd`/artifacts"
    - /usr/local/MATLAB/R2022a/bin/matlab -sd ./ -batch "runSRSGNBUnittest('all', 'testvector'); srsTest.copySRStestvectors('testvector_outputs', '$ARTIFACTSDIR')"

run unit tests:
  stage: run unit tests
  tags:
    - matlab
  variables:
    GIT_STRATEGY: clone
  artifacts:
    name: build testvectors
    paths:
    - artifacts/
  before_script:
    - export export SRSGNBDIR="`pwd`/srsgnb"
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/softwareradiosystems/srsgnb.git srsgnb
  script:
    - rsync -av ./artifacts/ $SRSGNBDIR
    - cd $SRSGNBDIR
    - |
      if [[ $(git ls-files --others|wc -l) -gt 0 ]]; then
        echo "The following files were not tracked by git:"
        echo `git ls-files --others`
        exit 1
      fi
    - |
      if [[ $(git ls-files --modified|wc -l) -eq 0 ]]; then
        echo "No test files were copied to the srsgnb working directory."
        exit 1
      fi
    - ctest --build-and-test $SRSGNBDIR $SRSGNBDIR/build --build-generator Ninja --test-command ctest -L phy
